
[config]
input = [
  "volume",
  "label"
]

logging = [
  '__train_iteration__', 
  'train.loss', 'valid.loss'
]

archive_nodes = ['CAE']
optimizing_loss = ['loss']

[hyper_parameter]
n_encode_dim = 512
n_layers = 3
gaussian_sigma = 20
n_res_layers = 4

[[process]]
label  = "CAE"
type   = "network.cae"
update = "loss"

# Arguments
n_dim = 3
in_channel = 1
out_channel = 1
encode_dim = "${hyper_parameter.n_encode_dim}"
dropout = "dropout"
use_batch_norm = true
n_layers = "${hyper_parameter.n_layers}"
latent_activation = false

# Network declaration

[[network]]
input="volume"
process="expand_dims"
output="volume_expanded"
axis=1

[[network]]
input=["volume_expanded", "label"]
process="to_gpu"
output=["gpu_volume",  "gpu_f_label"]

[[network]]
input="gpu_f_label"
process="cast_type"
dtype='int32'
output="gpu_label"

## Apply gaussian noise
[[network]]
input = "gpu_volume"
process = "apply_gaussian_noise"
output = "gpu_noisy_volume"

sigma = "${hyper_parameter.gaussian_sigma}"

## Reconstruct label
[[network]]
input="gpu_noisy_volume"
label="CAE"
process="CAE"
output="gpu_reconstruct_label_probs"

[[network]]
input=[ "gpu_reconstruct_label_probs", "gpu_label" ]
process="chainer.softmax_cross_entropy"
output="loss_reconstruct_label"

[[network]]
input="gpu_reconstruct_probs"
process="chainer.softmax"
output="gpu_reconstruct_label"

# Visualize declaration
[[visualize]]
type  = "image_write"
image_names = [ 
  "volume", "gpu_reconstruct_label"
  ]
output_filename = '${visualize_dir}/{__train_iteration__:08d}_{__name__}_{__index__}.mhd'
num_images = 3
