
[config]
input = [
  'image', 'body_bone_image', 'label'
]

logging = [
  '__train_iteration__', 
  'train.loss_sigmoid', 'valid.loss_sigmoid',
  'train.loss_softmax', 'valid.loss_softmax',
  'train.loss_unet', 'valid.loss_unet'
]

archive_nodes = ['Predictor']
optimizing_loss = ['loss_unet']

[hyper_parameter]
n_input_channel = 1
n_class = 1
threshold = 0.015

[[process]]
label  = "Predictor"
type   = "network.U-net"
update = "loss_unet"

in_channel = "${hyper_parameter.n_input_channel}"
out_channel = "${hyper_parameter.n_class}"


# Network declaration
## Make body bone label
[[network]]
input   = "body_bone_image"
process = "binary"
output  = "body_bone_label"

threshold = "${hyper_parameter.threshold}"

[[network]]
input=["image", "label", "body_bone_label"]
process="to_gpu"
output=["gpu_image_tmp", "gpu_label", "gpu_body_bone_label_tmp"]

# Input image is two dimensional but the shape of image must be (N, C, H, W).
# (N is batch size and will automatically concatenate on to_gpu)
[[network]]
input=  "gpu_image_tmp"
process="chainer.expand_dims"
output= "gpu_image"
axis=1

# Input image and predicted label are same shape due to sigmoid cross entropy.
# If you want to use softmax cross entropy, remove this section.
[[network]]
input  ="gpu_body_bone_label_tmp"
process="chainer.expand_dims"
output ="gpu_body_bone_label"
axis=1

[[network]]
input  ="gpu_body_bone_label"
process="cast_type"
dtype='float32'
output ="gpu_body_bone_label_float"

# Mask input image by body bone label
[[network]]
input  = ["gpu_image", "gpu_body_bone_label_float"]
process= "reduce"
operation = "*"
output = "gpu_masked_image"

# Predict label by unet
[[network]]
input="gpu_masked_image"
label="Predictor"
process="Predictor"
output="gpu_raw_pred_label"

## Losses
[[network]]
input=[ "gpu_raw_pred_label", "gpu_label" ]
process="chainer.sigmoid_cross_entropy"
output="loss_sigmoid"
normalize=false
test=false

## Activated pred label
[[network]]
input   = "gpu_raw_pred_label"
process = "chainer.sigmoid"
output  = "gpu_pred_label"

[[network]]
input=[ "gpu_pred_label", "gpu_label" ]
process="loss.total_softmax_cross_entropy"
output="loss_softmax"
normalize=false
test=false

[[network]]
input = ["loss_sigmoid", "loss_softmax"]
output = "loss_unet"
process = "reduce"
operation = "+"
test = false

## Index to Color label
[[network]]
input   = "gpu_label"
process = "map_index_label"
output  = "gpu_color_label"
train=false
test=false

[[network]]
input   = "gpu_pred_label"
process = "make_overlap_label"
output  = "gpu_color_pred_label"
train=false
test=false

## Expand label for visualization
# [[network]]
# input = "gpu_label"
# process = "chainer.expand_dims"
# axis = 1
# output = "gpu_label_4d"

## Blend DRR and label images.
[[network]]
input = ["gpu_image", "gpu_color_label", "gpu_image", "gpu_color_pred_label"]
process = "blend_image"
output = ["gpu_blend_label", "gpu_blend_pred_label"]
train=false
test=false

# Visualize declaration
[[visualize]]
type  = "image_write"
image_names = [ 
  "gpu_image", "body_bone_image", 
  "gpu_pred_label", "gpu_label" 
  ]
output_filename = '${visualize_dir}/{__train_iteration__:08d}_{__name__}_{__index__}.mhd'
num_images = 3

[[visualize]]
type = "tile_image_visualizer"
output_filename = "${visualize_dir}/{__train_iteration__:08d}_tile.png"
tile_shape = [5, 5]
block_images =  [ 
  'gpu_image',        'gpu_label',      'gpu_blend_label',    
  'gpu_masked_image', 'gpu_pred_label', 'gpu_blend_pred_label'
  ]
block_shape = [2, 3]

