
[config]
input = [
  'image', 'body_bone_image'
]

logging = [
  '__train_iteration__', 'train.loss_xentropy', 'valid.loss_xentropy'
]

archive_nodes = ['Predictor']
optimizing_loss = ['loss_xentropy']

[hyper_parameter]
n_input_channel = 1
n_output_channel = 1
threshold = 0.015

[[process]]
label  = "Predictor"
type   = "network.U-net"
update = "loss_xentropy"

in_channel = "${hyper_parameter.n_input_channel}"
out_channel = "${hyper_parameter.n_output_channel}"


# Network declaration

[[network]]
input   = "body_bone_image"
process = "binary"
output  = "label"

threshold = "${hyper_parameter.threshold}"

[[network]]
input=["image", "label"]
process="to_gpu"
output=["gpu_image", "gpu_label"]

[[network]]
input="gpu_image"
process="Predictor"
output="gpu_raw_pred_label"

## Losses
[[network]]
input=[ "gpu_raw_pred_label", "gpu_label" ]
process="chainer.sigmoid_cross_entropy"
output="loss_xentropy"

# Process for visualization
[[network]]
input   = "gpu_raw_pred_label"
process = "chainer.sigmoid"
output  = "gpu_pred_label"

[[network]]
input   = ["gpu_image", "gpu_label", "gpu_image", "gpu_pred_label"]
process = "make_overlap_label"
output  = ["gpu_overlap_label", "gpu_overlap_pred_label"]

# Visualize declaration
[[visualize]]
type  = "image_write"
image_names = [ 
  "gpu_image", "body_bone_image", 
  "gpu_pred_label", "gpu_label" 
  ]
output_filename = '${visualize_dir}/{__train_iteration__:08d}_{__index__}.mhd'
num_images = 3

[[visualize]]
type = "tile_image_visualizer"
output_filename = "${visualize_dir}/{__train_iteration__:08d}_tile.png"
tile_shape = [5, 5]
block_images =  [ 
  'gpu_image', 'gpu_label', 'gpu_overlap_label',
  'gpu_image', 'gpu_pred_label', 'gpu_overlap_pred_label'
  ]
block_shape = [2, 3]

# [[visualize]]
# type="plot"
# x="iteration"
# y=["loss_adv_xray", "loss_adv_drr"]
# event={ trigger="step", value="50" }

